_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "/home/yetao/zzk/few_shot/Efficient-FSOD/Output/split1/efc/retina_fpn/30shot/model_final.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  BACKBONE:
    FREEZE: True
    FREEZE_AT: 5
  PROPOSAL_GENERATOR:
    FREEZE: True
  RPN:
    POST_NMS_TOPK_TRAIN: 2000
  ROI_HEADS:
#    NAME: "ContrastiveROIHeads"
    NUM_CLASSES: 7
    BATCH_SIZE_PER_IMAGE: 256
    SCORE_THRESH_TEST: 0.01
  ROI_BOX_HEAD:
    CONTRASTIVE_BRANCH:
      TEMPERATURE: 0.2
      LOSS_WEIGHT: 0.2
      DECAY:
        ENABLED: True
#        STEPS: [2500, 3200]
        RATE: 0.5
      IOU_THRESHOLD: 0.6
#    PREDICTOR: "CosineSimOutputLayers"
    CLS_AGNOSTIC_BBOX_REG: True
    FREEZE: True
    LR_FACTOR: 0.5
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
DATASETS:
  TRAIN: ('voc_2007_trainval_split1_30shot',)
  TEST: ('voc_2007_test_split1_all',)
SOLVER:
  BASE_LR: 0.01
  STEPS: (3200,)
  WARMUP_ITERS: 100
  MAX_ITER: 4000
SETTING: 'Incremental'
PHASE: 2
METHOD: 'ours'
INIT_ITERS: 10
OUTPUT_DIR: "Output/ablation/30shot/no_ci_closs_rpn_roi"
TEST:
  EVAL_PERIOD: 100