_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "/home/yetao/zzk/few_shot/Efficient-FSOD/Output/split2/base/model_final.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_BOX_HEAD:
    CLS_AGNOSTIC_BBOX_REG: False
  ROI_HEADS:
    NUM_CLASSES: 15
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
DATASETS:
  TRAIN: ('voc_2007_trainval_split3_base', 'voc_2012_trainval_split3_base')
  TEST: ('voc_2007_test_split3_voc',)
SOLVER:
  STEPS: (12000, 16000)
  MAX_ITER: 18000
  WARMUP_ITERS: 100
PHASE: 1
OUTPUT_DIR: "Output/split3/base"