_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: ""
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  BACKBONE:
    FREEZE: True
    FREEZE_AT: 5
  PROPOSAL_GENERATOR:
    FREEZE: True
  RPN:
    POST_NMS_TOPK_TRAIN: 2000
  ROI_HEADS:
#    NAME: "ContrastiveROIHeads"
    NUM_CLASSES: 7
    BATCH_SIZE_PER_IMAGE: 256
    SCORE_THRESH_TEST: 0.01
  ROI_BOX_HEAD:
    CONTRASTIVE_BRANCH:
      TEMPERATURE: 0.2
      LOSS_WEIGHT: 0.2
      DECAY:
        ENABLED: True
        #        STEPS: [300, 600]
        RATE: 0.5
      IOU_THRESHOLD: 0.6
    CLS_AGNOSTIC_BBOX_REG: True
    FREEZE: True
    LR_FACTOR: 0.5
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
DATASETS:
  TRAIN: ('voc_2007_trainval_split1_5shot',)
  TEST: ('voc_2007_test_split1_all',)
SOLVER:
  BASE_LR: 0.02
  STEPS: (1500,)
  WARMUP_ITERS: 5
  MAX_ITER: 2000
  CHECKPOINT_PERIOD: 1000
SETTING: 'Incremental'
PHASE: 2
METHOD: 'ours'
INIT_ITERS: 10
OUTPUT_DIR: ""
TEST:
  EVAL_PERIOD: 4000