_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "/home/yetao/zzk/few_shot/Efficient-FSOD/Output/nosim_class/base/model_final.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  BACKBONE:
    FREEZE: True
    FREEZE_AT: 5
  RPN:
    POST_NMS_TOPK_TRAIN: 2000
  ROI_HEADS:
    NAME: "ContrastiveROIHeads"
    NUM_CLASSES: 22
    BATCH_SIZE_PER_IMAGE: 256
    SCORE_THRESH_TEST: 0.01
  ROI_BOX_HEAD:
    CONTRASTIVE_BRANCH:
      TEMPERATURE: 0.2
      LOSS_WEIGHT: 0.2
      DECAY:
        ENABLED: True
        #        STEPS: [300, 600]
        RATE: 0.5
      IOU_THRESHOLD: 0.6
    CLS_AGNOSTIC_BBOX_REG: True
    FREEZE: False
    LR_FACTOR: 0.5
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
DATASETS:
  TRAIN: ('voc_2007_trainval_split4_10shot', 'voc_2012_trainval_split4_10shot')
  TEST: ('voc_2007_test_split4_all',)
SOLVER:
  BASE_LR: 0.02
  STEPS: (3000,)
  WARMUP_ITERS: 100
  MAX_ITER: 4000
  CHECKPOINT_PERIOD: 200
SETTING: 'Incremental'
PHASE: 2
METHOD: 'ours'
INIT_ITERS: 10
OUTPUT_DIR: "Output/nosim_class/10allshot"
TEST:
  EVAL_PERIOD: 200